# Generated by Django 3.0.2 on 2020-01-21 12:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories_api.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories_api.Attributes')),
                ('products', models.ManyToManyField(through='categories_api.ProductValues', to='categories_api.Products')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='attributes',
            field=models.ManyToManyField(through='categories_api.CategoryAttributes', to='categories_api.Attributes'),
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
        migrations.AddField(
            model_name='productvalues',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories_api.Value'),
        ),
    ]
