# Generated by Django 3.0.2 on 2020-01-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_api', '0002_auto_20200121_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Value',
            new_name='Values',
        ),
    ]
